<?php

namespace Tests\Feature;

use App\Category;
use App\Item;
use Tests\TestCase;

class CategoryItemsControllerTest extends TestCase{

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        if (!Category::count()) {
            $this->seed('CategoriesSeeder');
        }

        if (!Item::count()) {
            $this->seed('ItemsSeeder');
        }
    }

    /** @test */
    public function it_can_see_category_items(){
        $category = Category::has('items')->first();
        $this->getJson("api/categories/{$category->id}/items")
            ->assertStatus(200)
            ->assertJsonStructure([
                'data' => [
                    '*' => [
                        'id', 'name', 'description', 'image', 'category_id', 'created_at',
                        'updated_at', 'image_url',
                    ]
                ]
            ]);
    }
}